name: 'snyk-sync'
description: 'Runs the snyk-sync scripts'
branding:
  icon: 'search'
  color: 'red'
inputs:
  arguments:
    description: 'snyk sync arguments to run'
    required: true
runs:
  using: 'docker'
  image: 'docker://mrzarquon/snyk-sync:latest'
  args:
    - ${{ inputs.arguments }}