name: create-import-data

on:
  workflow_dispatch:

jobs:
  create-org-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      - name: Run snyk-sync to generate targets
        uses: ./.github/actions/snyk-sync
        with:
          arguments: --sync
        env:
          SNYK_SYNC_GROUP: '36863d40-ba29-491f-af63-7a1a7d79e411'
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate list of potential projects to import
        uses: technote-space/create-pr-action@v2
        with:
          COMMIT_MESSAGE: 'chore: Update Orgs to Import'
          COMMIT_NAME: 'SnykBot 3000'
          COMMIT_EMAIL: 'example@example.com'
          PR_BRANCH_NAME: 'chore-api-import-update-${PR_ID}'
          PR_TITLE: 'chore: update org list'
        env:
          SNYK_LOG_PATH: 'org_data'
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}