name: create-import-data

on:
  workflow_dispatch:

jobs:
  create-org-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run snyk-sync to generate targets
        uses: ./.github/actions/snyk-sync
        with:
          arguments: --sync targets --save
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SNYK_GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Updated list of Repositories to Import
          title: Updated Repo List
          body: New repositories to be imported
          branch: update-import-targets
