name: perform-import

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 
    - name: Import Projects to snyk
      run: |
        echo "Snyk Secret 2 is: ${SNYK_SECRET}"
        /bin/bash scripts/install_snyk_tools.sh
        /bin/bash scripts/perform_import.sh
      env:
        SNYK_LOG_PATH: 'org_data'
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        SNYK_SECRET: ${{ secrets.SNYK_SECRET }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SNYK_IMPORT_PATH: "import-targets.json"
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
