name: perform-import

on:
  workflow_dispatch:

jobs:
  import-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run snyk-api-import to import new repositories
        uses: ./.github/actions/snyk-api-import
        with:
          arguments: import --file /github/workspace/targets/customer-success-engineering.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_IMPORT_PATH: "targets/customer-success-engineering.json"
          SNYK_LOG_PATH: "cache/logs"
      - name: Run snyk-sync to update tags
        uses: ./.github/actions/snyk-sync
        with:
          arguments: --sync tags --update
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SNYK_GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: API Import Logs and Tag Updates
          title: API Import Results
          body: Repositories and logs of last import
          branch: update-api-new-projects
